### PR TITLE
Fix panic in recurrence parsing

### PR DESCRIPTION
**Pull request by zmbush**

### CODE REVIEW

**Comment by sanpii** [comment]
I don’t understand how your modifications can fix a panic. Without the PR, the tests still passed. Can you add an problematic example?

**Comment by zmbush** [comment]
I did add a problematic example. Parsing a recurrence value of "+1" would panic, since it is not shorter than 2.

**Comment by sanpii** [comment]
Ok, I forgot to launch all tests…

Thank you!

**Comment by sanpii** [comment]
@zmbush Your PR made me realize that it’s not necessary to limit the size of a period. I improve the parse and remove all unwrap: https://github.com/sanpii/todo-txt/pull/18

**Pull request merged**
